### ISSUE TITLE
No license info

### ISSUE THREAD

**Issue by sghose-ttc** [sclasen/event-shuttle#1]
Hi Scott,

Event-shuttle looks really interesting, and was thinking of using it in one of my projects. Noticed there is no license info. in the repo. What type of license you are planning to use for the project?

**Comment by sclasen** [comment]
MIT works. will push one up shortly!

**Comment by wolfeidau** [comment]
+1 just road testing this now, looks great but just wanted to make sure license was up before I get in trouble :)

Thanks!

**Comment by sclasen** [comment]
@sghose-ttc sorry about that, just added MIT license  /cc @wolfeidau

**Comment by sghose-ttc** [comment]
Thanks a lot @sclasen. Appreciate it.
